# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=32)),
                ('session_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
