# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.TextField()),
                ('s_table', models.TextField()),
                ('log_type', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
