# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='it_owner',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='who_affected',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Site'),
        ),
    ]
